Rewrite function of network module, adding feeature fetch WLAN credentials from file - file/etc/network/interface file reorganized as follows:   auto dev1   allow-hotplug dev1   iface dev1   ...   <one empty line>   auto dev2   allow-hotplug dev2   iface dev2   ...
- Messed up file (multiple auto entries for device and empty lines) eliminated
- resAuto works for all eth, wlan and ra devices
- setInterfaceDisableFn works for all eth, wlan and ra devices. Terminating
  dhclient,  wpa_supplicant and wpa_cli for disabled device
- fetchInterfaceData function added. This allows reading WLAN credentials from
  current /etc/network/interfaces and /etc/wpa_supplicant/wpa_supplicant.conf
  file
- setInterfaceWlanCredentials: wireless-power off entry added
- When adding network device, allow-hotplug will be added for all devices
- checkValidGwFn did not handle IP comparison correctly
- /etc/network/interfaces contains WLAN credentials, so setting mode 0600
  is necessary
- Function scanWLANNetworksFn optimized (reading output of iwlist reverse),
  probably one issue (processing of last entry) fixed
  Storing output of iwlist in file /tmp/iwliststatus for debugging added

** GUI **
- disable of network interface modified. Beside commenting out
  iface .. and allow-hotplug ..., all further relevant entries are
  removed
- Interface disable message added
- showRestartGUIFn does not wait infinitely for device restart complete
  30s should be enough
- WLAN credentials (key) is fetched from /etc/wpa_supplicant/wpa_supplicant.conf
  if available.
- ra* as WLAN device added

** CMD **
- some isValidInterfaceFn removed because called function does this
- function xbian-config network credentials returns them if psk is omitted
  for WPA and WEP
- network device can set to disable state

diff --git a/content/usr/local/include/xbian-config/modules/network/main b/content/usr/local/include/xbian-config/modules/network/main
--- a/content/usr/local/include/xbian-config/modules/network/main
+++ b/content/usr/local/include/xbian-config/modules/network/main
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#Copyright 2012 - 2013 Hexagon, CurlyMo, mk01 & mkreisl <development@xbian.org>
+#Copyright 2012 - 2018 Hexagon, CurlyMo, mk01 & mkreisl <development@xbian.org>
 #
 #This file is part of XBian - XBMC on the Raspberry Pi.
 #
@@ -87,20 +87,18 @@ function showIPModeConfigGUIFn() {
 			STATUS=$?;
 			MODE="static"
 		else
-			setInterfaceDisableFn "$IFACE"
+			showInterfaceStaticGUIFn "$IFACE" "$IFACE_DATA" disable
 			STATUS=3
 		fi
 
 		if [ $STATUS -eq 1 ]; then
 			# If needed, ask for wireless credentials
-			ISWLAN=$(echo -e "$IFACE" | grep wlan)
+			ISWLAN=$(echo -e "$IFACE" | grep -E 'wlan|ra')
 			if [ ! -z "$ISWLAN" ]; then
 				showWlanScanGUIFn "$IFACE" "$IFACE_DATA"
 			else
 				# Configuration done
-				showRestartAdapterDlg "$IFACE"
-				restartAdapterFn "$IFACE"
-				setAuto "$IFACE"
+				showRestartGUIFn "$IFACE" "LAN"
 				showGUIFn
 			fi
 		fi
@@ -116,46 +114,52 @@ function showInterfaceStaticGUIFn() {
 	GATEWAY=$(echo "$2" | grep gateway | cut -f 2 -d" ")
 	NAMESERVER1=$(echo "$2" | grep nameserver1 | cut -f 2 -d" ")
 	NAMESERVER2=$(echo "$2" | grep nameserver2 | cut -f 2 -d" ")
-	
-	showInterfaceStaticDlg "$IP" "$NETMASK" "$GATEWAY" "$NAMESERVER1" "$NAMESERVER2"
-	if [ $? -eq 0 ]; then
+
+	if [ "$3" = "disable" ]; then
 		IFS=$'\n';
-		STATICCONF=($(echo -e "$RETURN"))
+		setInterfaceStaticFn "$1" "$IP" "$NETMASK" "$GATEWAY" "$NAMESERVER1" "$NAMESERVER2" $3
 		IFS=$ORIGINALIFS;
-		if [ ${#STATICCONF[@]} -gt 1 ]; then
-			IP="${STATICCONF[0]}"
-			NETMASK="${STATICCONF[1]}"
-			GATEWAY="${STATICCONF[2]}"
-			NAMESERVER1=""
-			NAMESERVER2=""
-			if [ ${#STATICCONF[@]} -gt 3 ]; then
-				NAMESERVER1="${STATICCONF[3]}"
-			fi
-			if [ ${#STATICCONF[@]} -gt 4 ]; then
-				NAMESERVER2="${STATICCONF[4]}"
-			fi
-			# Validation of arguments is done inside this function
-			RESULT=$(setInterfaceStaticFn "$1" "$IP" "$NETMASK" "$GATEWAY" "$NAMESERVER1" "$NAMESERVER2"; echo $?)
-			if [ $RESULT -eq 1 ]; then
-				showInterfaceStaticSuccessDlg
-				if [[ $1 =~ "wlan" ]]; then
-					showWlanScanGUIFn "$1" "$2"
+		showInterfaceDisableSuccessDlg
+		showGUIFn
+	else
+		showInterfaceStaticDlg "$IP" "$NETMASK" "$GATEWAY" "$NAMESERVER1" "$NAMESERVER2"
+		if [ $? -eq 0 ]; then
+			IFS=$'\n';
+			STATICCONF=($(echo -e "$RETURN"))
+			IFS=$ORIGINALIFS;
+			if [ ${#STATICCONF[@]} -gt 1 ]; then
+				IP="${STATICCONF[0]}"
+				NETMASK="${STATICCONF[1]}"
+				GATEWAY="${STATICCONF[2]}"
+				NAMESERVER1=""
+				NAMESERVER2=""
+				if [ ${#STATICCONF[@]} -gt 3 ]; then
+					NAMESERVER1="${STATICCONF[3]}"
+				fi
+				if [ ${#STATICCONF[@]} -gt 4 ]; then
+					NAMESERVER2="${STATICCONF[4]}"
+				fi
+				# Validation of arguments is done inside this function
+				RESULT=$(setInterfaceStaticFn "$1" "$IP" "$NETMASK" "$GATEWAY" "$NAMESERVER1" "$NAMESERVER2"; echo $?)
+				if [ $RESULT -eq 1 ]; then
+					showInterfaceStaticSuccessDlg
+					if [[ $1 =~ "wlan" ]] || [[ $1 =~ "ra" ]]; then
+						showWlanScanGUIFn "$1" "$2"
+					else
+						showRestartGUIFn $1 "LAN"
+						showGUIFn;
+					fi
 				else
-					showRestartAdapterDlg $1
-					restartAdapterFn $1
-					setAuto $1
-					showGUIFn;
+					showInterfaceStaticErrorDlg
+					showInterfaceStaticGUIFn "$1" "$2"
 				fi
 			else
 				showInterfaceStaticErrorDlg
 				showInterfaceStaticGUIFn "$1" "$2"
 			fi
 		else
-			showInterfaceStaticErrorDlg
-			showInterfaceStaticGUIFn "$1" "$2"
+			showIPModeConfigGUIFn
 		fi
-	else
-		showIPModeConfigGUIFn
 	fi
 }
 
@@ -192,8 +196,8 @@ function showWlanScanGUIFn() {
 					fi
 
 					if [ "$SSID" != "$(echo "${WNETWORK[0]}" | awk '{print substr($0,2,length-2)}')" ]; then
-						WLANKEY="";
 						SSID=$(echo "${WNETWORK[0]}" | awk '{print substr($0,2,length-2)}');
+						fetchWLANCredentialsFn "$PROTECTION" "$SSID"
 					fi
 					showWlanProtectionGUIFn "$1" "$2" "$PROTECTION" "$CUSTOM"
 				else
@@ -245,7 +249,7 @@ function showWlanProtectionGUIFn() {
 				fi
 				
 				showInterfaceCredentialsSuccessDlg
-				showWlanRestartGUIFn $1 $SSID
+				showRestartGUIFn $1 $SSID
 				if [ $STATUS -eq 2 ]; then
 					showGUIFn;
 				elif [ $STATUS -eq 3 ]; then
@@ -266,7 +270,7 @@ function showWlanProtectionGUIFn() {
 			if [ ! -z "$RETURN" ]; then
 				setInterfaceWlanCredentials "$1" "Open" "$RETURN"
 				showInterfaceCredentialsSuccessDlg
-				showWlanRestartGUIFn $1 $SSID
+				showRestartGUIFn $1 $SSID
 				if [ $STATUS -eq 3 ]; then
 					showGUIFn;
 				elif [ $STATUS -eq 2 ]; then
@@ -282,23 +286,22 @@ function showWlanProtectionGUIFn() {
 	fi
 }
 
-function showWlanRestartGUIFn() {
+function showRestartGUIFn() {
 	showRestartAdapterDlg $1
 	restartAdapterFn "$1"
-	LASTSTATUS=-1;
 	setAuto $1
-	while kill -0 $(cat /tmp/ifup.pid) 2>/dev/null; do
-		showWLANConnectingDlg $2
-		sleep 1
+	for i in $(seq 1 15); do
+		showConnectingDlg "$2 ($1)"
+		STATUS=$(showCMDFn progress $1)
+		[ "$STATUS" -eq 2 ] || break
+		sleep 2
 	done
-	getConnectStatusFn $1
 
-	if [ $STATUS -eq 2 ]; then
-		showWLANConnectionSuccessDlg $2
-	elif [ $STATUS -eq 3 ]; then
-		showWLANConnectionFailedDlg $2
+	if [ $STATUS -eq 1 ]; then
+		showConnectionSuccessDlg "$2 ($1)"
+	else
+		showConnectionFailedDlg "$2 ($1)"
 	fi
-	clearStatusFn;
 	return $STATUS;
 
 
@@ -344,7 +347,7 @@ function showCMDFn() {
 	case $1 in
 		list)
 			IFACES=$(listNetworkInterfacesFn)
-			if [ $? -eq 1 ] && [ ! -z "$IFACES" ]; then
+			if [ -n "$IFACES" ]; then
 				echo -e "$IFACES"
 				return 1;
 			else
@@ -379,9 +382,9 @@ function showCMDFn() {
 		dhcp)
 			# Check that we have 3 arguments ($1=action, $2=interface)
 			if [ $# -eq 2 ]; then
-				isValidInterfaceFn "$2"
+				# No need to check for valid interface here as setInterfaceDhcpFn does it
+				setInterfaceDhcpFn "$2"
 				if [ $? -eq 1 ]; then
-					setInterfaceDhcpFn "$2"
 					echo "1"
 					setAuto "$2"
 					return 1;
@@ -398,51 +401,49 @@ function showCMDFn() {
 		;;
 		static)
 			if [ $# -gt 3 ]; then
-				isValidInterfaceFn "$2"
-				if [ $? -eq 1 ]; then
+				# No need to check for valid interface here as setInterfaceStaticFn does it
 
-					# $3 = IP
-					# $4 = Netmask
-					# $5 = Gateway
-					# $6 = Nameserver1
-					# $7 = Nameserver2
-					# $8 = Method static/manual
+				# $3 = IP
+				# $4 = Netmask
+				# $5 = Gateway
+				# $6 = Nameserver1
+				# $7 = Nameserver2
+				# $8 = Method static/manual/disable
 
-					setAuto "$2"
-					# Handle optional name servers and method
-					[ $# -gt 5 ] && NAMESERVER1="$6" || NAMESERVER1=""
-					[ $# -gt 6 ] && NAMESERVER2="$7" || NAMESERVER2=""
-					[ $# -gt 7 ] && METHOD="$8"      || METHOD=""
+				# Handle optional name servers and method
+				[ $# -gt 5 ] && NAMESERVER1="$6" || NAMESERVER1=""
+				[ $# -gt 6 ] && NAMESERVER2="$7" || NAMESERVER2=""
+				[ $# -gt 7 ] && METHOD="$8"      || METHOD=""
 
-					# Validation of arguments is done inside this function
-					RESULT=$(setInterfaceStaticFn "$2" "$3" "$4" "$5" "$NAMESERVER1" "$NAMESERVER2" "$METHOD"; echo $?)
-					case $RESULT in
-						6)
-							echo -6;
-						;;
-						7)
-							echo -7;
-						;;
-						8)
-							echo -8;
-						;;
-						9)
-							echo -9;
-						;;
-						1)
-							echo 1;
-						;;
-						3)
-							echo -3;
-						;;
-					esac;
-					# Return status of setInterfaceModeFn
-					return $RESULT;
-				else
-					# Invalid interface
-					echo "-2"
-					return 0;
-				fi
+				# Validation of arguments is done inside this function
+				RESULT=$(setInterfaceStaticFn "$2" "$3" "$4" "$5" "$NAMESERVER1" "$NAMESERVER2" "$METHOD"; echo $?)
+				case $RESULT in
+					0)
+						# Invalid interface
+						echo -2;
+					;;
+					1)
+						[ "$METHOD" = disable ] || setAuto "$2"
+						echo 1;
+					;;
+					3)
+						echo -3;
+					;;
+					6)
+						echo -6;
+					;;
+					7)
+						echo -7;
+					;;
+					8)
+						echo -8;
+					;;
+					9)
+						echo -9;
+					;;
+				esac;
+				# Return status of setInterfaceStaticFn
+				return $RESULT;
 			else
 				# Wrong number of arguments
 				echo "-1"
@@ -451,39 +452,41 @@ function showCMDFn() {
 		;;
 		credentials)
 			if [ $# -gt 3 ]; then
-				isValidInterfaceFn "$2"
-				if [ $? -eq 1 ]; then
-					# Validation of the data is done inside this function
+				# No need to check for valid interface here as setInterfaceWlanCredentials does it
 
-					# $2 = Interface
-					# $3 = WPA|WEP|Open
-					# $4 = ESSID
-					# $5 = WLANKEY (semi-optional, only needed with WPA or WEP)
+				# $2 = Interface
+				# $3 = WPA|WEP|Open
+				# $4 = ESSID
+				# $5 = WLANKEY (semi-optional, only needed with WPA or WEP)
 
-					setAuto $2
-					WLANKEY=""
-					if [ $# -gt 4 ]; then
-						WLANKEY="$5"
-					fi
-
-					RETURN=$(setInterfaceWlanCredentials "$2" "$3" "$(echo $4 | base64 -d)" "$(echo $WLANKEY | base64 -d)"; echo $?)
-					case $RETURN in
-						2)
-							echo -10;
-						;;
-						1)
-							echo 1;
-						;;
-						3)
-							echo 3;
+				WLANKEY=""
+				if [ $# -gt 4 ]; then
+					WLANKEY="$5"
+				else
+					case $3 in
+						WPA|WEP)
+							fetchWLANCredentialsFn "$3" "$(echo $4 | base64 -d)"
+							echo "$WLANKEY"
+							return 1
 						;;
 					esac
-					return $?;
-				else
-					# Invalid interface
-					echo "-2"
-					return 0;
 				fi
+
+				RETURN=$(setInterfaceWlanCredentials "$2" "$3" "$(echo $4 | base64 -d)" "$(echo $WLANKEY | base64 -d)"; echo $?)
+				case $RETURN in
+					0)
+						# Invalid interface
+						echo -2;
+					;;
+					1)
+						echo 1;
+						setAuto $2
+					;;
+					2)
+						echo -10;
+					;;
+				esac
+				return $RETURN;
 			else
 				# Wrong number of arguments
 				echo "-1"
@@ -495,14 +498,15 @@ function showCMDFn() {
 				isValidInterfaceFn "$2"
 				if [ $? -eq 1 ]; then
 					scanWLANNetworksFn $2;
-					IFS=$ORIGNALIFS;
-					for WNETWORK in ${WNETWORKS[@]}; do
-						echo $WNETWORK;
+					for WNETWORK in "${WNETWORKS[@]}"; do
+						echo "$WNETWORK";
 					done
 				else
+					# Invalid interface
 					echo -2
 				fi
 			else
+				# Wrong (number of) arguments
 				echo -1
 			fi
 		;;
@@ -511,7 +515,7 @@ function showCMDFn() {
 				isValidInterfaceFn "$2"
 				if [ $? -eq 1 ]; then
 					restartAdapterFn $2
-					if [ "$PROCESSID" -gt 0 ]; then
+					if [ "$?" -gt 0 ]; then
 						setAuto $2
 						echo 1
 					else
@@ -525,7 +529,7 @@ function showCMDFn() {
 			fi
 		;;
 		progress)
-			if [ -e /tmp/ifup.pid ] && kill -0 $(cat /tmp/ifup.pid) 2>/dev/null; then
+			if [ -e /run/ifup.pid ] && kill -0 $(cat /run/ifup.pid) 2>/dev/null; then
 				echo 2
 			else
 				getConnectStatusFn $2;
@@ -533,10 +537,8 @@ function showCMDFn() {
 					echo -12;
 				elif [ $STATUS -eq 2 ]; then
 					echo 1;
-					clearStatusFn;
 				elif [ $STATUS -eq 3 ]; then
 					echo 0;
-					clearStatusFn;
 				fi
 
 			fi
