btrfs-auto-snapshot - xbiancopy: issues fixed - /run/kpartxmap.xbiancopy.$$ was never removed - error processing until copying subvolumes was broken, because subshell   does not update parents variables - in case of error broken image will be deleted now

diff --git a/content/usr/sbin/btrfs-auto-snapshot b/content/usr/sbin/btrfs-auto-snapshot
--- a/content/usr/sbin/btrfs-auto-snapshot
+++ b/content/usr/sbin/btrfs-auto-snapshot
@@ -235,11 +235,13 @@ do_snapshot ()
 
 do_remove_kpartx () 
 {
-    [ -e /run/kpartxmap.xbiancopy.$$ ] && . /run/kpartxmap.xbiancopy.$$
-    [ -n "$loopd" ] && while ! kpartx -d $loopd 1>/dev/null 2>&1; do sleep 5; done
-    [ -n "$loopd" ] && losetup -d $loopd 1>/dev/null 2>&1
+	[ -e /run/kpartxmap.xbiancopy.$$ ] && . /run/kpartxmap.xbiancopy.$$
+	[ -n "$loopd" ] && while ! kpartx -d $loopd 1>/dev/null 2>&1; do sleep 5; done
+	[ -n "$loopd" ] && losetup -d $loopd 1>/dev/null 2>&1
 
-    sysctl -p /etc/sysctl.d/xbian.conf > /dev/null 2>/dev/null
+	rm -f /run/kpartxmap.xbiancopy.$$
+	rm -f /run/rc.xbiancopy.$$
+	sysctl -p /etc/sysctl.d/xbian.conf > /dev/null 2>/dev/null
 }
 
 do_rename () 
@@ -449,7 +451,7 @@ while true; do
                     rmdir '${tmp_dir}' > /dev/null; \
                     mountpoint -q /tmp/btrfs-dest && umount -l /tmp/btrfs-dest; \
                     mountpoint -q /tmp/btrfs-source && umount -l /tmp/btrfs-source; \
-                    do_remove_kpartx; rm -f kpartxmap.xbiancopy.$$; mapAndMountFn umount; " INT TERM EXIT
+                    do_remove_kpartx; mapAndMountFn umount; " INT TERM EXIT
                 break
         fi
 
@@ -570,7 +572,7 @@ case $opt_command in
 		do_rename $(dirname $1)/@$tmpd $1_rollback
                 ;;
 	(xbiancopy)
-	        rc=0
+		echo "rc=0" >/run/rc.xbiancopy.$$
 	        XBIANCOPYLOG='/tmp/xbiancopy.log'
 	        if [ "$BACKGROUND" == 1 ]; then
 	            echo "$@" > $XBIANCOPYLOG
@@ -582,21 +584,21 @@ case $opt_command in
 	        fi
 		(
 		    sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
-		    [ $# -ne 2 ] && { echo "wrong aruments list"; rc=5; exit $rc; }
-		    [ "$(readlink -e $1)" = "$(readlink -e $2)" ] && { echo "source and destination can not be the same block device"; rc=5; exit $rc; }
+		    [ $# -ne 2 ] && { echo "wrong aruments list"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
+		    [ "$(readlink -e $1)" = "$(readlink -e $2)" ] && { echo "source and destination can not be the same block device"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 
 		    if [ $opt_dev != $1 ]; then
-		        [ ! -b $1 ] && echo "non existend source device" && { rc=5; exit $rc; }
+		        [ ! -b $1 ] && echo "non existend source device" && { rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 		        BTRFS_LIST=$(btrfs-auto-snapshot listvol --dev $1 //)
 		    fi
 
 		    mkdir -p /tmp/btrfs-dest
 		    if [ -n "$opt_img" ]; then
 		        fn=$(mapAndMountFn mount $2)
-		        [ "$?" -eq 0 ] || { echo "can not mount fs"; rc=5; exit $rc; }
+		        [ "$?" -eq 0 ] || { echo "can not mount fs"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 		        set -- $1 $fn
-		        [ -e "$2" ] && rm -f "$2"; touch "$2" || { echo "can not create img file"; rc=5; exit $rc; }
-		        [ "$(df -P "$2" | tail -1 | awk '{print $1}')" = "$(readlink -e $1)" ] && { echo "img file can not be created on the source filesystem"; rc=5; exit $rc; }
+		        [ -e "$2" ] && rm -f "$2"; touch "$2" || { echo "can not create img file"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
+		        [ "$(df -P "$2" | tail -1 | awk '{print $1}')" = "$(readlink -e $1)" ] && { echo "img file can not be created on the source filesystem"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 
 		        if grep -q "rootflags=subvol=" /proc/cmdline; then
 			    subvolumeextra=$(cat /proc/cmdline); subvolumeextra=${subvolumeextra#*rootflags=subvol=}; subvolumeextra=${subvolumeextra%%\/@*}
@@ -619,8 +621,9 @@ case $opt_command in
 			    size=$opt_size
 		        fi
 
-		        [ "$(printf "%s\n%s\n" $(df -h $2 | tail -1 | awk '{print $4}') "$size" | sort -rh | grep -m1 .)" = "$size" ] && { echo "not enough free space on destination filesystem"; rc=5; exit $rc; }
-		        chattr +CA $2 &>/dev/null;  truncate -s $size $2 || { echo "can't resize img file to needed size"; rc=5; exit $rc; }
+			echo "fn=$2" >>/run/kpartxmap.xbiancopy.$$
+		        [ "$(printf "%s\n%s\n" $(df -h $2 | tail -1 | awk '{print $4}') "$size" | sort -rh | grep -m1 .)" = "$size" ] && { echo "not enough free space on destination filesystem"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
+		        chattr +CA $2 &>/dev/null; truncate -s $size $2 || { echo "can't resize img file to needed size"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 		        modprobe -q loop
 
 		        parted -s $2 mklabel msdos
@@ -629,7 +632,7 @@ case $opt_command in
 		        echo "2048,$((config_offset_root-2048)),b,*," | sfdisk -uS -N1 -f -q $2 > /dev/null 2>&1
 		        echo "$config_offset_root,+,83,," | sfdisk -uS -N2 -f -q $2 > /dev/null 2>&1
 		        loopd=$(losetup -f); losetup $loopd $2
-		        kpartx -a $loopd && echo "loopd=$loopd" > /run/kpartxmap.xbiancopy.$$
+		        kpartx -a $loopd && echo "loopd=$loopd" >>/run/kpartxmap.xbiancopy.$$
 		        loopd=${loopd#/dev/}
 
 		        timeout=0
@@ -637,7 +640,7 @@ case $opt_command in
 		            timeout=$(($timeout+1))
 		            if [ $timeout -gt 10 ]; then
 			        echo "Loop device not available";
-			        rc=4; exit $rc;
+			        rc=4; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc;
 		            fi
 		            sleep 1;
 		        done
@@ -649,7 +652,7 @@ case $opt_command in
 		        else
 		            mkfs.msdos -F 16 -n xbianboot /dev/mapper/${loopd}p1 2>/dev/null 1>&2
 		        fi
-		        mount /dev/mapper/${loopd}p1 /tmp/btrfs-dest || { rc=5; exit $rc; }
+		        mount /dev/mapper/${loopd}p1 /tmp/btrfs-dest || { rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 
 		        [ "$BACKGROUND" == 1 ] && cp -av /boot/* /tmp/btrfs-dest || cp -a /boot/* /tmp/btrfs-dest &>/dev/null
 		        sync
@@ -681,76 +684,93 @@ case $opt_command in
 
 		    mkdir -p /tmp/btrfs-source
 		    mount -t btrfs -o noatime,subvol=/ $1 /tmp/btrfs-source
-		    eval $opt_remotecmd findmnt -n -S $2 >/dev/null && { eval $opt_remotecmd umount $2 || { echo "can not umount destination partition"; rc=5; exit $rc; }; }
+		    eval $opt_remotecmd findmnt -n -S $2 >/dev/null && { eval $opt_remotecmd umount $2 || { echo "can not umount destination partition"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }; }
 		    if [ -z "$opt_nocreate" ]; then
-		        eval $opt_remotecmd mkfs.btrfs -O skinny-metadata -m single -L $opt_clonename -f $2 2>&1 || { echo "can not format destination $2"; rc=5; exit $rc; }
+		        eval $opt_remotecmd mkfs.btrfs -O skinny-metadata -m single -L $opt_clonename -f $2 2>&1 || { echo "can not format destination $2"; rc=5; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc; }
 		    fi
 		    eval $opt_remotecmd mkdir -p /tmp/btrfs-dest
 
 		    if ! eval findmnt -n / | grep -q "compress=lz4" || ! eval $opt_remotecmd mount -o compress=lz4,noatime,thread_pool=1 $2 /tmp/btrfs-dest; then
 		        if ! eval $opt_remotecmd mount -o compress=lzo,noatime,thread_pool=1 $2 /tmp/btrfs-dest; then
 			    echo "can not mount destination partition"
-			    rc=6; exit $rc
+			    rc=6; echo "rc=$rc" >/run/rc.xbiancopy.$$; exit $rc
 		        fi
 		    fi
 
 		) | eval "$PIPECMD1"
 
-		[ "$rc" -ne 0 ] && exit $rc
+		. /run/rc.xbiancopy.$$
 
-		if grep -q "rootflags=subvol=" /proc/cmdline; then
-		    subvolumeextra=$(cat /proc/cmdline); subvolumeextra=${subvolumeextra#*rootflags=subvol=}; subvolumeextra=${subvolumeextra%%\/@*}
-		    export subvolumeextra
-		    snapextra=$(cat /proc/cmdline); snapextra=${snapextra#*rootflags=subvol=$subvolumeextra"/@"}; snapextra=${snapextra%%,*}
+		if [ "$rc" -eq 0 ]; then
+
+		    if grep -q "rootflags=subvol=" /proc/cmdline; then
+		        subvolumeextra=$(cat /proc/cmdline); subvolumeextra=${subvolumeextra#*rootflags=subvol=}; subvolumeextra=${subvolumeextra%%\/@*}
+		        export subvolumeextra
+		        snapextra=$(cat /proc/cmdline); snapextra=${snapextra#*rootflags=subvol=$subvolumeextra"/@"}; snapextra=${snapextra%%,*}
+		    fi
+
+		    (
+		        sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
+		        BTRFS_LIST=$(printf "%s\n%s\n" "$subvolumeextra" "$BTRFS_LIST" | sort | uniq)
+		        snapextra=$(printf "%s\n%s\n" "@$snapextra" "@"| sort | uniq)
+		        [ -n "$opt_debug" ] && [ "$BACKGROUND" == 1 ] && echo "DEBUG: BTRFS_LIST=$BTRFS_LIST, snapextra=$snapextra" >> $XBIANCOPYLOG
+		        for v in $BTRFS_LIST; do
+		            [ -n "$v" ] || continue
+		            eval $opt_remotecmd btrfs sub create "/tmp/btrfs-dest/$v"
+		            export v="$v"
+		            for s in $snapextra; do
+		                [ -n "$s" ] || continue
+		                [ -e "/tmp/btrfs-source/$v/$s" ] || continue
+		                #echo "DEBUG: v = $v, s = $s"
+		                [ -e "/tmp/btrfs-source/$v/$s.ro" ] && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro" > /dev/null 2>&1
+		                [ -e "/tmp/btrfs-source/$v/$s" ] || continue
+		                btrfs sub snap -r "/tmp/btrfs-source/$v/$s" "/tmp/btrfs-source/$v/$s.ro" && sync && btrfs fi sync "/tmp/btrfs-source/$v/$s.ro"
+			        export siz=$(du -sxb "/tmp/btrfs-source/$v/$s.ro" | awk '{print $1}'); export sn=$s; export vln=$v;
+			        [ "$siz" -gt 100000000 ] && export ival=20 || export ival=2
+			        ar=0
+		                ( nice -n 10 btrfs send "/tmp/btrfs-source/$v/$s.ro" | pv -i $ival -n -s $siz | eval $opt_remotecmd nice -n 10 btrfs receive "/tmp/btrfs-dest/$v" ) 2>&1 | \
+			            while read a; do
+			                if [ "$BACKGROUND" == 1 ]; then
+			                    if ! echo "$a" | grep -q '@'; then
+			                        if (( $a > $ar )); then
+			                            echo "$(printf 'Cloning %s/%s, %d of %d, %d%% done' $v $s $((siz*a/100)) $siz $a)"
+			                            ar=$a
+			                        fi
+			                    fi
+			                else
+			                    printf "XXX\n$a\n$(printf 'Cloning %s/%s. Total %d. Done %d' $v $s $siz $((siz*a/100)))\nXXX\n"
+			                fi
+			            done
+		                eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s.ro" && sync && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro"
+		                eval $opt_remotecmd nice -n 10 btrfs sub snap "/tmp/btrfs-dest/$v/$s.ro" "/tmp/btrfs-dest/$v/$s" && sync
+		                eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s"
+		                eval $opt_remotecmd nice -n 10 btrfs sub delete "/tmp/btrfs-dest/$v/$s.ro" && eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v"
+		                [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v snapshot $s"
+		            done
+		           [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v"
+		        done
+		    ) 2>&1 | eval "$PIPECMD2"
 		fi
 
 		(
-		    sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
-		    BTRFS_LIST=$(printf "%s\n%s\n" "$subvolumeextra" "$BTRFS_LIST" | sort | uniq)
-		    snapextra=$(printf "%s\n%s\n" "@$snapextra" "@"| sort | uniq)
-		    for v in $BTRFS_LIST; do
-		        [ -n "$v" ] || continue
-		        eval $opt_remotecmd btrfs sub create "/tmp/btrfs-dest/$v"
-		        export v="$v"
-		        for s in $snapextra; do
-		            [ -n "$s" ] || continue
-		            [ -e "/tmp/btrfs-source/$v/$s" ] || continue
-		            #echo "DEBUG: v = $v, s = $s"
-		            [ -e "/tmp/btrfs-source/$v/$s.ro" ] && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro" > /dev/null 2>&1
-		            [ -e "/tmp/btrfs-source/$v/$s" ] || continue
-		            btrfs sub snap -r "/tmp/btrfs-source/$v/$s" "/tmp/btrfs-source/$v/$s.ro" && sync && btrfs fi sync "/tmp/btrfs-source/$v/$s.ro"
-			    export siz=$(du -sxb "/tmp/btrfs-source/$v/$s.ro" | awk '{print $1}'); export sn=$s; export vln=$v;
-			    [ "$siz" -gt 100000000 ] && export ival=20 || export ival=2
-			    ar=0
-		            ( nice -n 10 btrfs send "/tmp/btrfs-source/$v/$s.ro" | pv -i $ival -n -s $siz | eval $opt_remotecmd nice -n 10 btrfs receive "/tmp/btrfs-dest/$v" ) 2>&1 | \
-			        while read a; do
-			            if [ "$BACKGROUND" == 1 ]; then
-			                if ! echo "$a" | grep -q '@'; then
-			                    if (( $a > $ar )); then
-			                        echo "$(printf 'Cloning %s/%s, %d of %d, %d%% done' $v $s $((siz*a/100)) $siz $a)"
-			                        ar=$a
-			                    fi
-			                fi
-			            else
-			                printf "XXX\n$a\n$(printf 'Cloning %s/%s. Total %d. Done %d' $v $s $siz $((siz*a/100)))\nXXX\n"
-			            fi
-			        done
-		            eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s.ro" && sync && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro"
-		            eval $opt_remotecmd nice -n 10 btrfs sub snap "/tmp/btrfs-dest/$v/$s.ro" "/tmp/btrfs-dest/$v/$s" && sync
-		            eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s"
-		            eval $opt_remotecmd nice -n 10 btrfs sub delete "/tmp/btrfs-dest/$v/$s.ro" && eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v"
-		            [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v snapshot $s"
-		        done
-		       [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v"
-		    done
-		) 2>&1 | eval "$PIPECMD2"
+		    eval $opt_remotecmd umount /tmp/btrfs-dest; eval $opt_remotecmd rmdir /tmp/btrfs-dest
+		    umount /tmp/btrfs-source; rmdir /tmp/btrfs-source
+		) &>/dev/null
 
-		eval $opt_remotecmd umount /tmp/btrfs-dest; eval $opt_remotecmd rmdir /tmp/btrfs-dest > /dev/null 2>&1
-		umount /tmp/btrfs-source; rmdir /tmp/btrfs-source
+                if [ "$rc" -eq 0 ]; then
+		    success_msg="Done!"
+                    [ -e ${CONFIGPATH} ] && { echo "$DATE" > ${CONFIGPATH}/$opt_command; chown xbian:xbian ${CONFIGPATH}/${opt_command}; }
+                elif [ -e /run/kpartxmap.xbiancopy.$$ ]; then
+		    success_msg="Fail!"
+                    . /run/kpartxmap.xbiancopy.$$
+                    [ "$BACKGROUND" == 1 ] && echo "Removing broken image file ${fn##*/}" >> $XBIANCOPYLOG
+                    rm -f $fn
+                fi
+
 		if [ "$BACKGROUND" == 1 ]; then
-		    echo "Done!" >> $XBIANCOPYLOG
+		    echo "$success_msg" >> $XBIANCOPYLOG
 		else
-		    dialog --clear --msgbox "Done!
+		    dialog --clear --msgbox "$success_msg
  
 for users on xbian version below beta2 (beta1.1, beta1). beta2 handles this automaticaly.
 /etc/fstab file needs to be adapted for /home to be mounted properly on the new xbian copy.
@@ -766,7 +786,6 @@ for all users - change /boot/cmdline.txt if you want to boot from the copy just 
 if you created img file, cmdline.txt was updated automatically." 24 79
 		fi
 		[ -e "/tmp/xbiancopy.running" ] && touch /tmp/xbiancopy.running.$(cat /tmp/xbiancopy.running)
-                [ -e ${CONFIGPATH} ] && { echo "$DATE" > ${CONFIGPATH}/$opt_command; chown xbian:xbian ${CONFIGPATH}/${opt_command}; }
 		;;
         (backuphome)
 	        BACKUPHOMELOG='/tmp/backuphome.log'
