Cosmetic, formatting code

diff --git a/content/usr/sbin/btrfs-auto-snapshot b/content/usr/sbin/btrfs-auto-snapshot
--- a/content/usr/sbin/btrfs-auto-snapshot
+++ b/content/usr/sbin/btrfs-auto-snapshot
@@ -581,118 +581,118 @@ case $opt_command in
 	            PIPECMD2="dialog --gauge \"Cloning all subvolumes. Please wait...\" 10 60"
 	        fi
 		(
-		sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
-		[ $# -ne 2 ] && { echo "wrong aruments list"; rc=5; exit $rc; }
-		[ "$(readlink -e $1)" = "$(readlink -e $2)" ] && { echo "source and destination can not be the same block device"; rc=5; exit $rc; }
+		    sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
+		    [ $# -ne 2 ] && { echo "wrong aruments list"; rc=5; exit $rc; }
+		    [ "$(readlink -e $1)" = "$(readlink -e $2)" ] && { echo "source and destination can not be the same block device"; rc=5; exit $rc; }
 
-		if [ $opt_dev != $1 ]; then
-		    [ ! -b $1 ] && echo "non existend source device" && { rc=5; exit $rc; }
-		    BTRFS_LIST=$(btrfs-auto-snapshot listvol --dev $1 //)
-		fi
-
-		mkdir -p /tmp/btrfs-dest
-		if [ -n "$opt_img" ]; then
-		    fn=$(mapAndMountFn mount $2)
-		    [ "$?" -eq 0 ] || { echo "can not mount fs"; rc=5; exit $rc; }
-		    set -- $1 $fn
-		    [ -e "$2" ] && rm -f "$2"; touch "$2" || { echo "can not create img file"; rc=5; exit $rc; }
-		    [ "$(df -P "$2" | tail -1 | awk '{print $1}')" = "$(readlink -e $1)" ] && { echo "img file can not be created on the source filesystem"; rc=5; exit $rc; }
-
-		    if grep -q "rootflags=subvol=" /proc/cmdline; then
-			subvolumeextra=$(cat /proc/cmdline); subvolumeextra=${subvolumeextra#*rootflags=subvol=}; subvolumeextra=${subvolumeextra%%\/@*}
-			export subvolumeextra
-			snapextra=$(cat /proc/cmdline); snapextra=${snapextra#*rootflags=subvol=$subvolumeextra"/@"}; snapextra=${snapextra%%,*}
-		    fi
-		    BTRFS_LIST=$(printf "%s\n%s\n" "$subvolumeextra" "$BTRFS_LIST" | sort | uniq)
-		    snapextra=$(printf "%s\n%s\n" "@$snapextra" "@"| sort | uniq)
-		    if [ "$opt_size" = "0" ]; then
-			for v in $BTRFS_LIST; do
-			    [ -n "$v" ] || continue
-			    export v="$v"
-			    for s in $snapextra; do
-				sv=$(btrfs-auto-snapshot volsize "$v/$s")
-				size=$((size+sv))
-			    done
-			done
-			size="$(($size*12/10/1024/1024))M"
-		    else
-			size=$opt_size
+		    if [ $opt_dev != $1 ]; then
+		        [ ! -b $1 ] && echo "non existend source device" && { rc=5; exit $rc; }
+		        BTRFS_LIST=$(btrfs-auto-snapshot listvol --dev $1 //)
 		    fi
 
-		    [ "$(printf "%s\n%s\n" $(df -h $2 | tail -1 | awk '{print $4}') "$size" | sort -rh | grep -m1 .)" = "$size" ] && { echo "not enough free space on destination filesystem"; rc=5; exit $rc; }
-		    chattr +CA $2 &>/dev/null;  truncate -s $size $2 || { echo "can't resize img file to needed size"; rc=5; exit $rc; }
-		    modprobe -q loop
+		    mkdir -p /tmp/btrfs-dest
+		    if [ -n "$opt_img" ]; then
+		        fn=$(mapAndMountFn mount $2)
+		        [ "$?" -eq 0 ] || { echo "can not mount fs"; rc=5; exit $rc; }
+		        set -- $1 $fn
+		        [ -e "$2" ] && rm -f "$2"; touch "$2" || { echo "can not create img file"; rc=5; exit $rc; }
+		        [ "$(df -P "$2" | tail -1 | awk '{print $1}')" = "$(readlink -e $1)" ] && { echo "img file can not be created on the source filesystem"; rc=5; exit $rc; }
 
-		    parted -s $2 mklabel msdos
-
-		    config_offset_root=141312
-		    echo "2048,$((config_offset_root-2048)),b,*," | sfdisk -uS -N1 -f -q $2 > /dev/null 2>&1
-		    echo "$config_offset_root,+,83,," | sfdisk -uS -N2 -f -q $2 > /dev/null 2>&1
-		    loopd=$(losetup -f); losetup $loopd $2
-		    kpartx -a $loopd && echo "loopd=$loopd" > /run/kpartxmap.xbiancopy.$$
-		    loopd=${loopd#/dev/}
-
-		    timeout=0
-		    while ! [ -L /dev/mapper/${loopd}p1 ]; do
-		        timeout=$(($timeout+1))
-		        if [ $timeout -gt 10 ]; then
-			    echo "Loop device not available";
-			    rc=4; exit $rc;
+		        if grep -q "rootflags=subvol=" /proc/cmdline; then
+			    subvolumeextra=$(cat /proc/cmdline); subvolumeextra=${subvolumeextra#*rootflags=subvol=}; subvolumeextra=${subvolumeextra%%\/@*}
+			    export subvolumeextra
+			    snapextra=$(cat /proc/cmdline); snapextra=${snapextra#*rootflags=subvol=$subvolumeextra"/@"}; snapextra=${snapextra%%,*}
 		        fi
-		        sleep 1;
-		    done		
-
-		    if [ "$(xbian-arch)" = iMX6 ]; then
-		        dd if=/etc/uboot-env/SPL of=/dev/$loopd bs=1K seek=1 2>/dev/null 1>&2
-		        dd if=/etc/uboot-env/u-boot.img of=/dev/$loopd bs=1K seek=42 2>/dev/null 1>&2 
-		        mkfs.ext2 -L xbianboot /dev/mapper/${loopd}p1 2>/dev/null 1>&2
-		    else
-		        mkfs.msdos -F 16 -n xbianboot /dev/mapper/${loopd}p1 2>/dev/null 1>&2
-		    fi
-		    mount /dev/mapper/${loopd}p1 /tmp/btrfs-dest || { rc=5; exit $rc; }
-
-		    [ "$BACKGROUND" == 1 ] && cp -av /boot/* /tmp/btrfs-dest || cp -a /boot/* /tmp/btrfs-dest &>/dev/null
-		    sync
-
-		    if [ "$(xbian-arch)" = RPI ]; then
-		        sed -i 's/^#initramfs /initramfs /' /tmp/btrfs-dest/config.txt
-		    fi
-		    if [ "$(xbian-arch)" = iMX6 ]; then
-		        [ -e /boot/initramfs.gz.notinuse -a ! -e /boot/initramfs.gz ] && mv /tmp/btrfs-dest/initramfs.gz.notinuse /tmp/btrfs-dest/initramfs.gz
-		    fi
-
-		    z=$(grep -o "root=[^ ]*" /proc/cmdline)
-		    if echo $z | grep -q "root=LABEL"; then
-		        if test -e /boot/cmdline.txt; then
-			    sed -i "s%$z%root=LABEL=$opt_clonename%" /tmp/btrfs-dest/cmdline.txt
+		        BTRFS_LIST=$(printf "%s\n%s\n" "$subvolumeextra" "$BTRFS_LIST" | sort | uniq)
+		        snapextra=$(printf "%s\n%s\n" "@$snapextra" "@"| sort | uniq)
+		        if [ "$opt_size" = "0" ]; then
+			   for v in $BTRFS_LIST; do
+			        [ -n "$v" ] || continue
+			        export v="$v"
+			        for s in $snapextra; do
+			            sv=$(btrfs-auto-snapshot volsize "$v/$s")
+				    size=$((size+sv))
+			        done
+			   done
+			   size="$(($size*12/10/1024/1024))M"
+		        else
+			    size=$opt_size
 		        fi
-		        if test -e /boot/boot.scr.txt; then
-			    pushd . >/dev/null
-			    cd  /tmp/btrfs-dest
-			    sed -i "s%$z%root=LABEL=$opt_clonename%" boot.scr.txt
-			    ./mks
-			    popd >/dev/null
-			fi
+
+		        [ "$(printf "%s\n%s\n" $(df -h $2 | tail -1 | awk '{print $4}') "$size" | sort -rh | grep -m1 .)" = "$size" ] && { echo "not enough free space on destination filesystem"; rc=5; exit $rc; }
+		        chattr +CA $2 &>/dev/null;  truncate -s $size $2 || { echo "can't resize img file to needed size"; rc=5; exit $rc; }
+		        modprobe -q loop
+
+		        parted -s $2 mklabel msdos
+
+		        config_offset_root=141312
+		        echo "2048,$((config_offset_root-2048)),b,*," | sfdisk -uS -N1 -f -q $2 > /dev/null 2>&1
+		        echo "$config_offset_root,+,83,," | sfdisk -uS -N2 -f -q $2 > /dev/null 2>&1
+		        loopd=$(losetup -f); losetup $loopd $2
+		        kpartx -a $loopd && echo "loopd=$loopd" > /run/kpartxmap.xbiancopy.$$
+		        loopd=${loopd#/dev/}
+
+		        timeout=0
+		        while ! [ -L /dev/mapper/${loopd}p1 ]; do
+		            timeout=$(($timeout+1))
+		            if [ $timeout -gt 10 ]; then
+			        echo "Loop device not available";
+			        rc=4; exit $rc;
+		            fi
+		            sleep 1;
+		        done
+
+		        if [ "$(xbian-arch)" = iMX6 ]; then
+		            dd if=/etc/uboot-env/SPL of=/dev/$loopd bs=1K seek=1 2>/dev/null 1>&2
+		            dd if=/etc/uboot-env/u-boot.img of=/dev/$loopd bs=1K seek=42 2>/dev/null 1>&2
+		            mkfs.ext2 -L xbianboot /dev/mapper/${loopd}p1 2>/dev/null 1>&2
+		        else
+		            mkfs.msdos -F 16 -n xbianboot /dev/mapper/${loopd}p1 2>/dev/null 1>&2
+		        fi
+		        mount /dev/mapper/${loopd}p1 /tmp/btrfs-dest || { rc=5; exit $rc; }
+
+		        [ "$BACKGROUND" == 1 ] && cp -av /boot/* /tmp/btrfs-dest || cp -a /boot/* /tmp/btrfs-dest &>/dev/null
+		        sync
+
+		        if [ "$(xbian-arch)" = RPI ]; then
+		            sed -i 's/^#initramfs /initramfs /' /tmp/btrfs-dest/config.txt
+		        fi
+		        if [ "$(xbian-arch)" = iMX6 ]; then
+		            [ -e /boot/initramfs.gz.notinuse -a ! -e /boot/initramfs.gz ] && mv /tmp/btrfs-dest/initramfs.gz.notinuse /tmp/btrfs-dest/initramfs.gz
+		        fi
+
+		        z=$(grep -o "root=[^ ]*" /proc/cmdline)
+		        if echo $z | grep -q "root=LABEL"; then
+		            if test -e /boot/cmdline.txt; then
+			        sed -i "s%$z%root=LABEL=$opt_clonename%" /tmp/btrfs-dest/cmdline.txt
+		            fi
+		            if test -e /boot/boot.scr.txt; then
+			        pushd . >/dev/null
+			        cd  /tmp/btrfs-dest
+			        sed -i "s%$z%root=LABEL=$opt_clonename%" boot.scr.txt
+			        ./mks
+			        popd >/dev/null
+			    fi
+		        fi
+
+		        while ! umount /tmp/btrfs-dest; do ! mountpoint -q /tmp/btrfs-dest && break; sleep 1; done; rmdir /tmp/btrfs-dest; sync
+		        set -- $1 /dev/mapper/${loopd}p2
 		    fi
 
-		    while ! umount /tmp/btrfs-dest; do ! mountpoint -q /tmp/btrfs-dest && break; sleep 1; done; rmdir /tmp/btrfs-dest; sync
-		    set -- $1 /dev/mapper/${loopd}p2
-		fi
-
-		mkdir -p /tmp/btrfs-source
-		mount -t btrfs -o noatime,subvol=/ $1 /tmp/btrfs-source
-		eval $opt_remotecmd findmnt -n -S $2 >/dev/null && { eval $opt_remotecmd umount $2 || { echo "can not umount destination partition"; rc=5; exit $rc; }; }
-		if [ -z "$opt_nocreate" ]; then
-		    eval $opt_remotecmd mkfs.btrfs -O skinny-metadata -m single -L $opt_clonename -f $2 2>&1 || { echo "can not format destination $2"; rc=5; exit $rc; }
-		fi
-		eval $opt_remotecmd mkdir -p /tmp/btrfs-dest
-
-		if ! eval findmnt -n / | grep -q "compress=lz4" || ! eval $opt_remotecmd mount -o compress=lz4,noatime,thread_pool=1 $2 /tmp/btrfs-dest; then
-		    if ! eval $opt_remotecmd mount -o compress=lzo,noatime,thread_pool=1 $2 /tmp/btrfs-dest; then
-			echo "can not mount destination partition"
-			rc=6; exit $rc
+		    mkdir -p /tmp/btrfs-source
+		    mount -t btrfs -o noatime,subvol=/ $1 /tmp/btrfs-source
+		    eval $opt_remotecmd findmnt -n -S $2 >/dev/null && { eval $opt_remotecmd umount $2 || { echo "can not umount destination partition"; rc=5; exit $rc; }; }
+		    if [ -z "$opt_nocreate" ]; then
+		        eval $opt_remotecmd mkfs.btrfs -O skinny-metadata -m single -L $opt_clonename -f $2 2>&1 || { echo "can not format destination $2"; rc=5; exit $rc; }
 		    fi
-		fi
+		    eval $opt_remotecmd mkdir -p /tmp/btrfs-dest
+
+		    if ! eval findmnt -n / | grep -q "compress=lz4" || ! eval $opt_remotecmd mount -o compress=lz4,noatime,thread_pool=1 $2 /tmp/btrfs-dest; then
+		        if ! eval $opt_remotecmd mount -o compress=lzo,noatime,thread_pool=1 $2 /tmp/btrfs-dest; then
+			    echo "can not mount destination partition"
+			    rc=6; exit $rc
+		        fi
+		    fi
 
 		) | eval "$PIPECMD1"
 
@@ -703,45 +703,46 @@ case $opt_command in
 		    export subvolumeextra
 		    snapextra=$(cat /proc/cmdline); snapextra=${snapextra#*rootflags=subvol=$subvolumeextra"/@"}; snapextra=${snapextra%%,*}
 		fi
+
 		(
-		sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
-		BTRFS_LIST=$(printf "%s\n%s\n" "$subvolumeextra" "$BTRFS_LIST" | sort | uniq)
-		snapextra=$(printf "%s\n%s\n" "@$snapextra" "@"| sort | uniq)
-		for v in $BTRFS_LIST; do
-		    [ -n "$v" ] || continue
-		    eval $opt_remotecmd btrfs sub create "/tmp/btrfs-dest/$v"
-		    export v="$v"
-		    for s in $snapextra; do
-		        [ -n "$s" ] || continue
-		        [ -e "/tmp/btrfs-source/$v/$s" ] || continue
-		        #echo "DEBUG: v = $v, s = $s"
-		        [ -e "/tmp/btrfs-source/$v/$s.ro" ] && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro" > /dev/null 2>&1
-		        [ -e "/tmp/btrfs-source/$v/$s" ] || continue 
-		        btrfs sub snap -r "/tmp/btrfs-source/$v/$s" "/tmp/btrfs-source/$v/$s.ro" && sync && btrfs fi sync "/tmp/btrfs-source/$v/$s.ro"
-			export siz=$(du -sxb "/tmp/btrfs-source/$v/$s.ro" | awk '{print $1}'); export sn=$s; export vln=$v;
-			[ "$siz" -gt 100000000 ] && export ival=20 || export ival=2
-			ar=0
-		        ( nice -n 10 btrfs send "/tmp/btrfs-source/$v/$s.ro" | pv -i $ival -n -s $siz | eval $opt_remotecmd nice -n 10 btrfs receive "/tmp/btrfs-dest/$v" ) 2>&1 | \
-			    while read a; do
-			        if [ "$BACKGROUND" == 1 ]; then
-			           if ! echo "$a" | grep -q '@'; then
-			               if (( $a > $ar )); then
-			                   echo "$(printf 'Cloning %s/%s, %d of %d, %d%% done' $v $s $((siz*a/100)) $siz $a)"
-			                   ar=$a
-			               fi
-			           fi
-			        else
-			           printf "XXX\n$a\n$(printf 'Cloning %s/%s. Total %d. Done %d' $v $s $siz $((siz*a/100)))\nXXX\n"
-			        fi
-			    done
-		        eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s.ro" && sync && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro"
-		        eval $opt_remotecmd nice -n 10 btrfs sub snap "/tmp/btrfs-dest/$v/$s.ro" "/tmp/btrfs-dest/$v/$s" && sync
-		        eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s"
-		        eval $opt_remotecmd nice -n 10 btrfs sub delete "/tmp/btrfs-dest/$v/$s.ro" && eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v"
-		        [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v snapshot $s"
+		    sysctl -w fs.file-max=80000 > /dev/null 2>/dev/null
+		    BTRFS_LIST=$(printf "%s\n%s\n" "$subvolumeextra" "$BTRFS_LIST" | sort | uniq)
+		    snapextra=$(printf "%s\n%s\n" "@$snapextra" "@"| sort | uniq)
+		    for v in $BTRFS_LIST; do
+		        [ -n "$v" ] || continue
+		        eval $opt_remotecmd btrfs sub create "/tmp/btrfs-dest/$v"
+		        export v="$v"
+		        for s in $snapextra; do
+		            [ -n "$s" ] || continue
+		            [ -e "/tmp/btrfs-source/$v/$s" ] || continue
+		            #echo "DEBUG: v = $v, s = $s"
+		            [ -e "/tmp/btrfs-source/$v/$s.ro" ] && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro" > /dev/null 2>&1
+		            [ -e "/tmp/btrfs-source/$v/$s" ] || continue
+		            btrfs sub snap -r "/tmp/btrfs-source/$v/$s" "/tmp/btrfs-source/$v/$s.ro" && sync && btrfs fi sync "/tmp/btrfs-source/$v/$s.ro"
+			    export siz=$(du -sxb "/tmp/btrfs-source/$v/$s.ro" | awk '{print $1}'); export sn=$s; export vln=$v;
+			    [ "$siz" -gt 100000000 ] && export ival=20 || export ival=2
+			    ar=0
+		            ( nice -n 10 btrfs send "/tmp/btrfs-source/$v/$s.ro" | pv -i $ival -n -s $siz | eval $opt_remotecmd nice -n 10 btrfs receive "/tmp/btrfs-dest/$v" ) 2>&1 | \
+			        while read a; do
+			            if [ "$BACKGROUND" == 1 ]; then
+			                if ! echo "$a" | grep -q '@'; then
+			                    if (( $a > $ar )); then
+			                        echo "$(printf 'Cloning %s/%s, %d of %d, %d%% done' $v $s $((siz*a/100)) $siz $a)"
+			                        ar=$a
+			                    fi
+			                fi
+			            else
+			                printf "XXX\n$a\n$(printf 'Cloning %s/%s. Total %d. Done %d' $v $s $siz $((siz*a/100)))\nXXX\n"
+			            fi
+			        done
+		            eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s.ro" && sync && btrfs sub delete "/tmp/btrfs-source/$v/$s.ro"
+		            eval $opt_remotecmd nice -n 10 btrfs sub snap "/tmp/btrfs-dest/$v/$s.ro" "/tmp/btrfs-dest/$v/$s" && sync
+		            eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v/$s"
+		            eval $opt_remotecmd nice -n 10 btrfs sub delete "/tmp/btrfs-dest/$v/$s.ro" && eval $opt_remotecmd nice -n 10 btrfs fi sync "/tmp/btrfs-dest/$v"
+		            [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v snapshot $s"
+		        done
+		       [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v"
 		    done
-		   [ "$BACKGROUND" == 1 ] && printf "%s\n" "Done copying subvolume $v"
-		done
 		) 2>&1 | eval "$PIPECMD2"
 
 		eval $opt_remotecmd umount /tmp/btrfs-dest; eval $opt_remotecmd rmdir /tmp/btrfs-dest > /dev/null 2>&1
