CLI interface to xbiancopy function

diff --git a/content/usr/local/include/xbian-config/modules/xbiancopy/main b/content/usr/local/include/xbian-config/modules/xbiancopy/main
--- a/content/usr/local/include/xbian-config/modules/xbiancopy/main
+++ b/content/usr/local/include/xbian-config/modules/xbiancopy/main
@@ -17,6 +17,10 @@
 #
 #You should have received a copy of the GNU General Public License along
 #with XBian. If not, see <http://www.gnu.org/licenses/>
+
+# The arguments this module accepts
+ARGUMENTS=(start status);
+
 #|------------------------------------|
 #|          Include files             |
 #|------------------------------------|
@@ -52,28 +56,42 @@ function showGUIFn() {
 
 # Executes the command line version of this module
 #  $1 Argument [String]
-# status | select | start | stop | restart | autostart | insert | update | delete
-#  $2 Service [String]
-# autostart
-#  $3 Action [String] Possible values 'enable' or 'disable'
-# insert | update
-#  $3 Daemons
-# Returns
-# -  4: Running but autostart disabled
-# -  3: Not running but autostart enabled
-# -  2: Not running and autostart disabled
-# -  1: Success
-# -  0: Failed
-# - -1: Invalid number of arguments
-# - -2: Service not available
-# - -3: Service already running
-# - -4: Service already stopped
-# - -5: Autostart already enabled
-# - -6: Autostart already disabled
-# - -7: Service file does not exists
+# status | start source destination [fs label] [[size]]
+#  (for size, human readable symbols are accepted (800M, 1G, 1T...)
+#
+# status return code
+# 1 ready
+# 0 running
+# -1 failed
+# -2 not started
+# 
+# start return code
+# number - pid of started backup process
+# -1 failed
 function showCMDFn() {
-	case $1 in
-		list)
-		;;
-	esac
+    case $1 in
+        start)
+            [ $# -lt 3 ] && { echo "-1"; exit 5; }
+            # [ -n "$4" ] && lab="--label  
+            [ -n "$5" ] && size="--size"
+            echo "$3" | grep -q ^'file:' && opt_img='--img'
+            dest="$3" && dest=${dest##'file:'}
+            nice -n +1 /usr/sbin/btrfs-auto-snapshot xbiancopy $size $5 $opt_img $2 $dest  > /dev/null 2>&1 & pid=$!
+            echo $pid > /tmp/xbiancopy.running
+            echo $pid
+            ;;
+        status)
+            [ -e /tmp/xbiancopy.running ] || { echo "-2"; exit 0; }
+            if [ -e /tmp/xbiancopy.running.$(cat /tmp/xbiancopy.running) ]; then
+                rm -f "/tmp/xbiancopy.running.$(cat /tmp/xbiancopy.running)"
+                rm -f /tmp/xbiancopy.running
+                echo "1"
+            else
+                kill -0 $(cat /tmp/xbiancopy.running) > /dev/null 2>&1 || { echo "-1"; rm -f /tmp/xbiancopy.running; }
+                echo "0"
+            fi
+            ;;
+    esac
+
+    exit 0
 }
